stages:
  - prep
  - build


build-fc32-x86_64:
  stage: prep
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp project.spec ~/rpmbuild/SPECS/
    - rm -rf ~/rpmbuild/SOURCES/*
    - cp SOURCES/* ~/rpmbuild/SOURCES/


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc32-x86_64 project.spec /mnt/repo/atomic-testing/fedora/32/x86_64 ; else  gitlab-build.sh fc32-x86_64 project.spec /mnt/repo/atomic-bleeding/fedora/32/x86_64 ; fi )


# Kali ??
# EOL: ??
build-kali-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - rm -rf ~/rpmbuild/BUILD/* || true
    - cp *.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - git clone https://gitlab.dev.atomicorp.com/atomicrocketturtle/buildsys-tools
    - cp buildsys-tools/* ~/bin/
    - chmod +x ~/bin/build-debian.sh

  script:
    -  (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  dist=kali arch=amd64 ~/bin/build-debian.sh -b project.spec /mnt/repo/atomic-testing/debian/; else  dist=kali arch=amd64 ~/bin/build-debian.sh -b project.spec /mnt/repo/atomic-bleeding/debian/; fi )


build-xenial-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - rm -rf ~/rpmbuild/BUILD/* || true
    - cp *.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - git clone https://gitlab.dev.atomicorp.com/atomicrocketturtle/buildsys-tools
    - cp buildsys-tools/* ~/bin/
    - chmod +x ~/bin/build-debian.sh

  script:
    -  (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  dist=xenial arch=amd64 ~/bin/build-debian.sh -b project.spec /mnt/repo/atomic-testing/debian/; else  dist=xenial arch=amd64 ~/bin/build-debian.sh -b project.spec /mnt/repo/atomic-bleeding/debian/; fi )


build-el7-x86_64:
  stage: prep
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp *.spec ~/rpmbuild/SPECS/
    - rm -rf ~/rpmbuild/SOURCES/*
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    

  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el7-x86_64 project.spec /mnt/repo/atomic-testing/centos/7/x86_64/ ; else  gitlab-build.sh el7-x86_64 project.spec /mnt/repo/atomic-bleeding/centos/7/x86_64/ ; fi )

build-el8-x86_64:
  stage: prep
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp *.spec ~/rpmbuild/SPECS/
    - rm -rf ~/rpmbuild/SOURCES/*
    - cp SOURCES/* ~/rpmbuild/SOURCES/


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el8-x86_64 project.spec /mnt/repo/atomic-testing/centos/8/x86_64/ ; else  gitlab-build.sh el8-x86_64 project.spec /mnt/repo/atomic-bleeding/centos/8/x86_64/ ; fi )


